### ISSUE TITLE
Contact address

### ISSUE THREAD

**Issue by annevk** [ExE-Boss/ExE-Boss#1]
Hey Exe-Boss,

The WHATWG Steering Group (sg@whatwg.org) would like to ask you about something. Is there a way to email or direct message you?

Kind regards,

Anne van Kesteren

**Comment by foolip** [comment]
Ping @ExE-Boss, we'd still like to get in touch. The topic is licensing of Web IDL :)

**Comment by ExE-Boss** [comment]
@annevk @foolip
> Is there a way to email or direct message you?

<del>I’ll send</del> <i>I’ve sent</i> an email from my private address to the **WHATWG Steering Group** signed with the same key as my commits to the **[WebIDL](https://github.com/heycam/webidl)** repository, that is, GPG key ID: `BF4FA5DD733D8D1A` (as seen in <https://github.com/ExE-Boss/webidl/commit/b1becf3d2538bbba1e10286cebc212827b89cc07>).

> The topic is licensing of Web IDL :)

What is the desired license that **WebIDL** is expected to be licensed under?

**Comment by annevk** [comment]
Thanks @ExE-Boss! You should have an email about the license grant. The license will be the same as that used for other WHATWG standards.
